if(NOT DEFINED LMCRACK_EXE OR NOT DEFINED LMHASH_EXE)
  message(FATAL_ERROR "LMCRACK_EXE and LMHASH_EXE required")
endif()
if(NOT DEFINED TEST_VERSION)
  set(TEST_VERSION 5)
endif()
foreach(alphabet ABC ABCDE)
  string(LENGTH "${alphabet}" size)
  math(EXPR last "${size}-1")
  string(SUBSTRING "${alphabet}" ${last} 1 end_char)
  foreach(a RANGE 0 ${last})
    foreach(b RANGE 0 ${last})
      string(SUBSTRING "${alphabet}" ${a} 1 first)
      string(SUBSTRING "${alphabet}" ${b} 1 second)
      set(password "${first}${second}A")
      execute_process(COMMAND "${LMHASH_EXE}" "${password}"
        RESULT_VARIABLE result OUTPUT_VARIABLE hash_output TIMEOUT 10)
      if(NOT result EQUAL 0 OR NOT hash_output MATCHES "Half LM Hash: ([0-9A-F]+)")
        message(FATAL_ERROR "hash generation failed")
      endif()
      set(hash "${CMAKE_MATCH_1}")
      # Full pair block exercises every stream and non-divisible pair tails.
      # Starting at the target additionally exercises shortened initial blocks.
      foreach(start AAA "${password}")
        execute_process(COMMAND "${LMCRACK_EXE}" "${hash}" -v1 "-v${TEST_VERSION}" -c "${alphabet}"
          -s "${start}" -e "${end_char}${end_char}A" -t 1
          RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
        string(REGEX MATCHALL "found password : ${password}(\r|\n)" matches "${output}")
        list(LENGTH matches count)
        if(NOT result EQUAL 0 OR NOT count EQUAL 2)
          message(FATAL_ERROR "${alphabet}/${password}/${start}: ${result}\n${output}\n${error}")
        endif()
      endforeach()
    endforeach()
  endforeach()
endforeach()
