# CMake generated Testfile for 
# Source directory: C:/work/research/gitlab/passwords/lmcrack
# Build directory: C:/work/research/gitlab/passwords/lmcrack/build-avx2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(v8_cli "C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "7584248B8D2C9F9E" "-v8" "-s" "A" "-e" "A" "-t" "1")
set_tests_properties(v8_cli PROPERTIES  PASS_REGULAR_EXPRESSION "found password : A" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;55;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_cli_normalized_alphabet "C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "7584248B8D2C9F9E" "-v8" "-c" "zyxwvutsrqponmlkjihgfedcba" "-s" "A" "-e" "A" "-t" "1")
set_tests_properties(v8_cli_normalized_alphabet PROPERTIES  PASS_REGULAR_EXPRESSION "found password : A" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;59;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_cli_reject_alphabet "C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "7584248B8D2C9F9E" "-v8" "-c" "ABC" "-s" "A" "-e" "A" "-t" "1")
set_tests_properties(v8_cli_reject_alphabet PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;64;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_cli "C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "25AD3B83FA6627C7" "-v9" "-s" "0" "-e" "0" "-t" "1")
set_tests_properties(v9_cli PROPERTIES  PASS_REGULAR_EXPRESSION "found password : 0" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;67;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_cli_normalized_alphabet "C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "25AD3B83FA6627C7" "-v9" "-c" "zyxwvutsrqponmlkjihgfedcba9876543210" "-s" "0" "-e" "0" "-t" "1")
set_tests_properties(v9_cli_normalized_alphabet PROPERTIES  PASS_REGULAR_EXPRESSION "found password : 0" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;71;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_cli_reject_alphabet "C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "25AD3B83FA6627C7" "-v9" "-c" "ABCDEFGHIJKLMNOPQRSTUVWXYZ" "-s" "A" "-e" "A" "-t" "1")
set_tests_properties(v9_cli_reject_alphabet PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;76;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_cli_differential "C:/Strawberry/c/bin/cmake.exe" "-DLMCRACK_EXE=C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "-P" "C:/work/research/gitlab/passwords/lmcrack/tests/integration/v9_cli_differential.cmake")
set_tests_properties(v9_cli_differential PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;80;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_cli "C:/work/research/gitlab/passwords/lmcrack/build-avx2/lmcrack.exe" "695109AB020E401C" "-v11" "-s" "!" "-e" "!" "-t" "1")
set_tests_properties(v11_cli PROPERTIES  PASS_REGULAR_EXPRESSION "found password : !" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;83;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_cli_integration "C:/Strawberry/c/bin/cmake.exe" "-DDESTOOL_EXE=C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool.exe" "-P" "C:/work/research/gitlab/passwords/lmcrack/tests/integration/destool_cli.cmake")
set_tests_properties(destool_cli_integration PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;87;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_benchmark_smoke "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_benchmark.exe" "-d" "1" "-w" "0" "-t" "1" "-a" "5" "-l" "3")
set_tests_properties(destool_benchmark_smoke PROPERTIES  PASS_REGULAR_EXPRESSION "result: candidates=[1-9][0-9]*.*rate=[0-9]+" _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;90;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_uppercase "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_uppercase_test.exe")
set_tests_properties(v8_uppercase PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;94;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_alnum "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_alnum_test.exe")
set_tests_properties(v9_alnum PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;95;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_bitslice_counter "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_bitslice_counter_test.exe")
set_tests_properties(v9_bitslice_counter PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;96;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_key_planes "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_key_planes_test.exe")
set_tests_properties(v9_key_planes PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;97;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_generator_diff "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_generator_diff_test.exe")
set_tests_properties(v9_generator_diff PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;98;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(fixed_bitslice_des "C:/work/research/gitlab/passwords/lmcrack/build-avx2/fixed_bitslice_des_test.exe")
set_tests_properties(fixed_bitslice_des PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;99;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_worker "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_worker_test.exe")
set_tests_properties(v9_worker PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;100;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_printable "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_printable_test.exe")
set_tests_properties(v11_printable PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;101;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_generator "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_generator_test.exe")
set_tests_properties(v11_generator PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;102;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_worker "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_worker_test.exe")
set_tests_properties(v11_worker PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;103;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_bitslice_counter "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_bitslice_counter_test.exe")
set_tests_properties(v8_bitslice_counter PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;104;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_key_planes "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_key_planes_test.exe")
set_tests_properties(v8_key_planes PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;105;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_generator_diff "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_generator_diff_test.exe")
set_tests_properties(v8_generator_diff PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;106;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_direct_des "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_direct_des_test.exe")
set_tests_properties(v8_direct_des PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;107;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_target "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_target_test.exe")
set_tests_properties(v8_target PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;108;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_worker "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_worker_test.exe")
set_tests_properties(v8_worker PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;109;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_vec "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_vec_test.exe")
set_tests_properties(bitslice_vec PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;110;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_batch "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_batch_test.exe")
set_tests_properties(bitslice_batch PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;111;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_transpose "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_transpose_test.exe")
set_tests_properties(bitslice_transpose PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;112;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_key "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_key_test.exe")
set_tests_properties(bitslice_key PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;113;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_sbox "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_sbox_test.exe")
set_tests_properties(bitslice_sbox PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;114;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_des "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_des_test.exe")
set_tests_properties(bitslice_des PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;115;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_block "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_block_test.exe")
set_tests_properties(bitslice_block PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;116;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_match "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_match_test.exe")
set_tests_properties(bitslice_match PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;117;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_lm "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_lm_test.exe")
set_tests_properties(bitslice_lm PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;118;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_target "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_target_test.exe")
set_tests_properties(bitslice_target PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;119;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_types "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_types_test.exe")
set_tests_properties(destool_types PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;120;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_alphabet "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_alphabet_test.exe")
set_tests_properties(destool_alphabet PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;121;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_bitslice_counter "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_bitslice_counter_test.exe")
set_tests_properties(destool_bitslice_counter PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;122;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_key_planes "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_key_planes_test.exe")
set_tests_properties(destool_key_planes PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;124;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_generator_diff "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_generator_diff_test.exe")
set_tests_properties(destool_generator_diff PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;125;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_worker "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_worker_test.exe")
set_tests_properties(destool_worker PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;127;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_cli "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_cli_test.exe")
set_tests_properties(destool_cli PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;128;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_runner "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_runner_test.exe")
set_tests_properties(destool_runner PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;129;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_recovery "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_recovery_test.exe")
set_tests_properties(destool_recovery PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;130;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_random_diff "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_random_diff_test.exe")
set_tests_properties(destool_random_diff PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;131;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_generator_diff_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_generator_diff_scalar_test.exe")
set_tests_properties(v8_generator_diff_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;167;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_bitslice_counter_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_bitslice_counter_scalar_test.exe")
set_tests_properties(v9_bitslice_counter_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;169;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_key_planes_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_key_planes_scalar_test.exe")
set_tests_properties(v9_key_planes_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;171;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_generator_diff_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_generator_diff_scalar_test.exe")
set_tests_properties(v9_generator_diff_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;173;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_worker_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_worker_scalar_test.exe")
set_tests_properties(v9_worker_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;175;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_generator_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_generator_scalar_test.exe")
set_tests_properties(v11_generator_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;177;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_worker_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_worker_scalar_test.exe")
set_tests_properties(v11_worker_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;179;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_target_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_target_scalar_test.exe")
set_tests_properties(v8_target_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;181;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_worker_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_worker_scalar_test.exe")
set_tests_properties(v8_worker_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;183;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_lm_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_lm_scalar_test.exe")
set_tests_properties(bitslice_lm_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;185;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_bitslice_counter_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_bitslice_counter_scalar_test.exe")
set_tests_properties(destool_bitslice_counter_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;187;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_key_planes_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_key_planes_scalar_test.exe")
set_tests_properties(destool_key_planes_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;190;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_generator_diff_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_generator_diff_scalar_test.exe")
set_tests_properties(destool_generator_diff_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;192;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_worker_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_worker_scalar_test.exe")
set_tests_properties(destool_worker_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;195;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_recovery_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_recovery_scalar_test.exe")
set_tests_properties(destool_recovery_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;197;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_random_diff_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_random_diff_scalar_test.exe")
set_tests_properties(destool_random_diff_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;199;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_target_scalar "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_target_scalar_test.exe")
set_tests_properties(bitslice_target_scalar PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;201;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_lm_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_lm_sse2_test.exe")
set_tests_properties(bitslice_lm_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;245;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_generator_diff_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_generator_diff_sse2_test.exe")
set_tests_properties(v8_generator_diff_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;247;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_bitslice_counter_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_bitslice_counter_sse2_test.exe")
set_tests_properties(v9_bitslice_counter_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;249;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_key_planes_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_key_planes_sse2_test.exe")
set_tests_properties(v9_key_planes_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;251;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_generator_diff_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_generator_diff_sse2_test.exe")
set_tests_properties(v9_generator_diff_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;253;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_worker_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_worker_sse2_test.exe")
set_tests_properties(v9_worker_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;255;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_generator_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_generator_sse2_test.exe")
set_tests_properties(v11_generator_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;257;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_worker_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_worker_sse2_test.exe")
set_tests_properties(v11_worker_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;259;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_target_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_target_sse2_test.exe")
set_tests_properties(v8_target_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;261;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_worker_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_worker_sse2_test.exe")
set_tests_properties(v8_worker_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;263;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_bitslice_counter_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_bitslice_counter_sse2_test.exe")
set_tests_properties(destool_bitslice_counter_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;265;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_key_planes_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_key_planes_sse2_test.exe")
set_tests_properties(destool_key_planes_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;268;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_generator_diff_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_generator_diff_sse2_test.exe")
set_tests_properties(destool_generator_diff_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;270;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_worker_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_worker_sse2_test.exe")
set_tests_properties(destool_worker_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;273;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_recovery_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_recovery_sse2_test.exe")
set_tests_properties(destool_recovery_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;275;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_random_diff_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_random_diff_sse2_test.exe")
set_tests_properties(destool_random_diff_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;277;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_target_sse2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_target_sse2_test.exe")
set_tests_properties(bitslice_target_sse2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;279;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_lm_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_lm_avx2_test.exe")
set_tests_properties(bitslice_lm_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;282;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_bitslice_counter_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_bitslice_counter_avx2_test.exe")
set_tests_properties(v9_bitslice_counter_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;284;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_key_planes_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_key_planes_avx2_test.exe")
set_tests_properties(v9_key_planes_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;286;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_generator_diff_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_generator_diff_avx2_test.exe")
set_tests_properties(v9_generator_diff_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;288;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v9_worker_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v9_worker_avx2_test.exe")
set_tests_properties(v9_worker_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;290;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_generator_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_generator_avx2_test.exe")
set_tests_properties(v11_generator_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;292;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v11_worker_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v11_worker_avx2_test.exe")
set_tests_properties(v11_worker_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;294;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_generator_diff_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_generator_diff_avx2_test.exe")
set_tests_properties(v8_generator_diff_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;296;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_target_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_target_avx2_test.exe")
set_tests_properties(v8_target_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;298;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(v8_worker_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/v8_worker_avx2_test.exe")
set_tests_properties(v8_worker_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;300;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_bitslice_counter_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_bitslice_counter_avx2_test.exe")
set_tests_properties(destool_bitslice_counter_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;302;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_key_planes_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_key_planes_avx2_test.exe")
set_tests_properties(destool_key_planes_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;305;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_generator_diff_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_generator_diff_avx2_test.exe")
set_tests_properties(destool_generator_diff_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;308;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_worker_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_worker_avx2_test.exe")
set_tests_properties(destool_worker_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;311;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_recovery_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_recovery_avx2_test.exe")
set_tests_properties(destool_recovery_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;313;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(destool_random_diff_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/destool_random_diff_avx2_test.exe")
set_tests_properties(destool_random_diff_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;315;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
add_test(bitslice_target_avx2 "C:/work/research/gitlab/passwords/lmcrack/build-avx2/bitslice_target_avx2_test.exe")
set_tests_properties(bitslice_target_avx2 PROPERTIES  _BACKTRACE_TRIPLES "C:/work/research/gitlab/passwords/lmcrack/cmake/LmcrackTests.cmake;42;add_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;318;lmcrack_add_cpp_test;C:/work/research/gitlab/passwords/lmcrack/CMakeLists.txt;0;")
